AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  iheart-backend

  Sample SAM Template for iheart-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: graphql.graphqlHandler
      Runtime: nodejs12.x
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: get
        PostRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
